# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EVG.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EVG(object):
    def setupUi(self, EVG):
        EVG.setObjectName("EVG")
        EVG.resize(1636, 1471)
        self.gridLayout = QtWidgets.QGridLayout(EVG)
        self.gridLayout.setObjectName("gridLayout")
        self.GBClocks = QtWidgets.QGroupBox(EVG)
        self.GBClocks.setObjectName("GBClocks")
        self.gridLayout.addWidget(self.GBClocks, 1, 0, 1, 1)
        self.GBControl = QtWidgets.QGroupBox(EVG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GBControl.sizePolicy().hasHeightForWidth())
        self.GBControl.setSizePolicy(sizePolicy)
        self.GBControl.setObjectName("GBControl")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.GBControl)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PyDMCbEVGEnable = PyDMCheckbox(self.GBControl)
        self.PyDMCbEVGEnable.setToolTip("")
        self.PyDMCbEVGEnable.setWhatsThis("")
        self.PyDMCbEVGEnable.setObjectName("PyDMCbEVGEnable")
        self.gridLayout_2.addWidget(self.PyDMCbEVGEnable, 0, 1, 1, 1)
        self.PyDMLedEVGEnable = PyDMLed(self.GBControl)
        self.PyDMLedEVGEnable.setToolTip("")
        self.PyDMLedEVGEnable.setWhatsThis("")
        self.PyDMLedEVGEnable.setObjectName("PyDMLedEVGEnable")
        self.gridLayout_2.addWidget(self.PyDMLedEVGEnable, 0, 0, 1, 1)
        self.PyDMLed = PyDMLed(self.GBControl)
        self.PyDMLed.setToolTip("")
        self.PyDMLed.setWhatsThis("")
        self.PyDMLed.setObjectName("PyDMLed")
        self.gridLayout_2.addWidget(self.PyDMLed, 1, 0, 1, 1)
        self.PyDMCbTableEnable = PyDMCheckbox(self.GBControl)
        self.PyDMCbTableEnable.setToolTip("")
        self.PyDMCbTableEnable.setWhatsThis("")
        self.PyDMCbTableEnable.setObjectName("PyDMCbTableEnable")
        self.gridLayout_2.addWidget(self.PyDMCbTableEnable, 0, 4, 1, 1)
        self.PyDMSpinBox = PyDMSpinBox(self.GBControl)
        self.PyDMSpinBox.setToolTip("")
        self.PyDMSpinBox.setWhatsThis("")
        self.PyDMSpinBox.setObjectName("PyDMSpinBox")
        self.gridLayout_2.addWidget(self.PyDMSpinBox, 1, 2, 1, 1)
        self.PyDMLedTableEnable = PyDMLed(self.GBControl)
        self.PyDMLedTableEnable.setToolTip("")
        self.PyDMLedTableEnable.setWhatsThis("")
        self.PyDMLedTableEnable.setObjectName("PyDMLedTableEnable")
        self.gridLayout_2.addWidget(self.PyDMLedTableEnable, 0, 3, 1, 1)
        self.PyDMCheckbox = PyDMCheckbox(self.GBControl)
        self.PyDMCheckbox.setToolTip("")
        self.PyDMCheckbox.setWhatsThis("")
        self.PyDMCheckbox.setObjectName("PyDMCheckbox")
        self.gridLayout_2.addWidget(self.PyDMCheckbox, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.PyDMLabel = PyDMLabel(self.GBControl)
        self.PyDMLabel.setToolTip("")
        self.PyDMLabel.setWhatsThis("")
        self.PyDMLabel.setObjectName("PyDMLabel")
        self.gridLayout_2.addWidget(self.PyDMLabel, 1, 3, 1, 1)
        self.PyDMLbTableStatus = PyDMLabel(self.GBControl)
        self.PyDMLbTableStatus.setToolTip("")
        self.PyDMLbTableStatus.setWhatsThis("")
        self.PyDMLbTableStatus.setObjectName("PyDMLbTableStatus")
        self.gridLayout_2.addWidget(self.PyDMLbTableStatus, 0, 5, 1, 1)
        self.gridLayout.addWidget(self.GBControl, 0, 0, 1, 1)
        self.GBEvents = QtWidgets.QGroupBox(EVG)
        self.GBEvents.setObjectName("GBEvents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.GBEvents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SAEvents = QtWidgets.QScrollArea(self.GBEvents)
        self.SAEvents.setWidgetResizable(True)
        self.SAEvents.setObjectName("SAEvents")
        self.WDEvents = QtWidgets.QWidget()
        self.WDEvents.setGeometry(QtCore.QRect(0, 0, 780, 1309))
        self.WDEvents.setObjectName("WDEvents")
        self.SAEvents.setWidget(self.WDEvents)
        self.verticalLayout.addWidget(self.SAEvents)
        self.gridLayout.addWidget(self.GBEvents, 1, 1, 1, 1)
        self.GBTables = QtWidgets.QGroupBox(EVG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GBTables.sizePolicy().hasHeightForWidth())
        self.GBTables.setSizePolicy(sizePolicy)
        self.GBTables.setObjectName("GBTables")
        self.gridLayout.addWidget(self.GBTables, 0, 1, 1, 1)

        self.retranslateUi(EVG)
        QtCore.QMetaObject.connectSlotsByName(EVG)

    def retranslateUi(self, EVG):
        _translate = QtCore.QCoreApplication.translate
        EVG.setWindowTitle(_translate("EVG", "Form"))
        self.GBClocks.setTitle(_translate("EVG", "Clocks"))
        self.GBControl.setTitle(_translate("EVG", "Control"))
        self.PyDMCbEVGEnable.setText(_translate("EVG", "Enable EVG"))
        self.PyDMCbTableEnable.setText(_translate("EVG", "Enable Tables"))
        self.PyDMCheckbox.setText(_translate("EVG", "AC Line Enable"))
        self.PyDMLbTableStatus.setText(_translate("EVG", "STATUS"))
        self.GBEvents.setTitle(_translate("EVG", "Events"))
        self.GBTables.setTitle(_translate("EVG", "Tables"))

from pydm.widgets.checkbox import PyDMCheckbox
from pydm.widgets.label import PyDMLabel
from pydm.widgets.led import PyDMLed
from pydm.widgets.spinbox import PyDMSpinBox
