"""Utilities."""


SEC_2_CHANNELS = {
    'BO': {
        'Emergency': 'BO-05D:RF-Intlk:EStop-Mon',
        'Sirius Intlk': 'RA-RaBO02:RF-IntlkCtrl:IntlkSirius-Mon',
        'LLRF Intlk': 'RA-RaBO01:RF-LLRF:Intlk-Mon',
        'LLRF Intlk Details': {
            'Inputs': {
                'Input': {
                    'Status': {
                        '0': 'BR-RF-DLLRF-01:ILK:0',
                        '1': 'BR-RF-DLLRF-01:ILK:1',
                        '2': 'BR-RF-DLLRF-01:ILK:2',
                        '3': 'BR-RF-DLLRF-01:ILK:3',
                        '4': 'BR-RF-DLLRF-01:ILK:4',
                        '5': 'BR-RF-DLLRF-01:ILK:5',
                        '6': 'BR-RF-DLLRF-01:ILK:6',
                        '7': 'BR-RF-DLLRF-01:ILK:7',
                        'Mon': 'BR-RF-DLLRF-01:Intlk-Mon',
                    },
                    'Labels': (
                        'Rev Out SSA',
                        'Not Used (RevSSA2)',
                        'Not Used (RefSSA3)',
                        'Not Used (RevSSA4)',
                        'Rev Cavity',
                        'Not Used (Ext LLRF1)',
                        'Not Used (Ext LLRF2)',
                        'Not Used (Ext LLRF3)',
                        'Manual',
                        'PLC',
                        'Plunger 1 End Sw Up',
                        'Plunger 1 End Sw Down',
                        'Plunger 2 End Sw Up',
                        'Plunger 2 End Sw Down',
                    ),
                },
                'Fast Input': {
                    'Status': {
                        '0': 'BR-RF-DLLRF-01:FAST:ILK:0',
                        '1': 'BR-RF-DLLRF-01:FAST:ILK:1',
                        '2': 'BR-RF-DLLRF-01:FAST:ILK:2',
                        '3': 'BR-RF-DLLRF-01:FAST:ILK:3',
                        '4': 'BR-RF-DLLRF-01:FAST:ILK:4',
                        '5': 'BR-RF-DLLRF-01:FAST:ILK:5',
                        '6': 'BR-RF-DLLRF-01:FAST:ILK:6',
                        '7': 'BR-RF-DLLRF-01:FAST:ILK:7',
                        'Mon': 'BR-RF-DLLRF-01:FASTINLK-MON',
                    },
                    'Labels': (
                        'Cavity Voltage',
                        'Cavity Fwd',
                        'SSA 1 Out Fwd',
                        'Cell 2 Voltage (RFIN7)',
                        'Cell 4 Voltage (RFIN8)',
                        'Cell 1 Voltage (RFIN9)',
                        'Cell 5 Voltage (RFIN10)',
                        'Pre-Drive In (RFIN11)',
                        'Pre-Drive Out Fwd (RFIN12)',
                        'Pre-Drive Out Rev (RFIN13)',
                        'Circulator Out Fwd (RFIN14)',
                        'Circulator Out Rev (RFIN15)',
                        'LLRF Beam Trip',
                    ),
                }
            },
            'Timestamps': {
                '1': 'BR-RF-DLLRF-01:TS1',
                '2': 'BR-RF-DLLRF-01:TS2',
                '3': 'BR-RF-DLLRF-01:TS3',
                '4': 'BR-RF-DLLRF-01:TS4',
                '5': 'BR-RF-DLLRF-01:TS5',
                '6': 'BR-RF-DLLRF-01:TS6',
                '7': 'BR-RF-DLLRF-01:TS7',
            }
        },
        'Reset': {
            'Global': 'RA-RaBO02:RF-Intlk:Reset-Cmd',
            'LLRF': 'BR-RF-DLLRF-01:Reset-Cmd',
        },
        'Cav Sts': {
            'Geral': 'BO-05D:RF-P5Cav:Sts-Mon',
            'Temp': {
                'Cells': (
                    ('BO-05D:RF-P5Cav:Cylin1T-Mon', 'blue'),
                    ('BO-05D:RF-P5Cav:Cylin2T-Mon', 'red'),
                    ('BO-05D:RF-P5Cav:Cylin3T-Mon', 'darkGreen'),
                    ('BO-05D:RF-P5Cav:Cylin4T-Mon', 'magenta'),
                    ('BO-05D:RF-P5Cav:Cylin5T-Mon', 'darkCyan'),
                ),
                'Cells Limits PVs': ('BO-05D:RF-P5Cav:Cylin1TLowerLimit-Cte',
                                     'BO-05D:RF-P5Cav:Cylin1TUpperLimit-Cte'),
                'Cells Limits': [0.0, 0.0],
                'Coupler': ('BO-05D:RF-P5Cav:CoupT-Mon', 'black'),
                'Coupler Limits PVs': ('BO-05D:RF-P5Cav:CoupTLowerLimit-Cte',
                                       'BO-05D:RF-P5Cav:CoupTUpperLimit-Cte'),
                'Coupler Limits': [0.0, 0.0],
                'Discs': (
                    'BO-05D:RF-P5Cav:Disc1Tms-Mon',
                    'BO-05D:RF-P5Cav:Disc2Tms-Mon',
                    'BO-05D:RF-P5Cav:Disc3Tms-Mon',
                    'BO-05D:RF-P5Cav:Disc4Tms-Mon',
                    'BO-05D:RF-P5Cav:Disc5Tms-Mon',
                    'BO-05D:RF-P5Cav:Disc6Tms-Mon',
                ),
            },
            'FlwRt': (
                'BO-05D:RF-P5Cav:Hd1FlwRt-Mon',
                'BO-05D:RF-P5Cav:Hd2FlwRt-Mon',
                'BO-05D:RF-P5Cav:Hd3FlwRt-Mon',
            ),
            'Vac': {
                'Cells': 'BO-05D:VA-CCG-RFC:Pressure-Mon',
                'Cond': 'BR-RF-DLLRF-01:VACUUM',
                'Cells ok': 'BO-05D:RF-P5Cav:Pressure-Mon',
                'Coupler ok': 'BO-05D:RF-P5Cav:CoupPressure-Mon',
            }
        },
        'TL Sts': {
            'Geral': 'RA-TLBO:RF-TrLine:Sts-Mon',
            'Circ TIn': 'RA-TLBO:RF-Circulator:Tin-Mon',
            'Circ TOut': 'RA-TLBO:RF-Circulator:Tout-Mon',
            'Circ Arc': 'RA-TLBO:RF-Circulator:Arc-Mon',
            'Circ FlwRt': 'RA-TLBO:RF-Circulator:FlwRt-Mon',
            'Load FlwRt': 'RA-TLBO:RF-Load:FlwRt-Mon',
            'Circ Intlk': 'RA-TLBO:RF-Circulator:IntlkOp-Mon',
            'Circ Limits': (19.0, 23.0),
        },
        'SSA': {
            'Name': 'SSA',
            'Status': 'RA-ToBO:RF-SSAmpTower:Sts-Mon',
            'Power': 'RA-ToBO:RF-SSAmpTower:PwrFwdOutLLRF-Mon',
            'SRC 1': {
                'Label': '300VDC',
                'PV': 'RA-ToBO:RF-ACDCPanel:300Vdc-Sts',
            },
            'SRC 2': {
                'Label': 'DC/DC',
                'PV': 'RA-ToBO:RF-SSAmpTower:PwrCnv-Sts',
            },
            'PinSw': 'RA-RaBO01:RF-LLRFPreAmp:PinSw-Mon',
            'PreDrive': 'BR-RF-DLLRF-01:INPRE:AMP',
        },
        'SL': {
            'Enbl': 'BR-RF-DLLRF-01:SL',
            'Mode': 'BR-RF-DLLRF-01:MODE',
            'IRef': 'BR-RF-DLLRF-01:I:SL:REF',
            'QRef': 'BR-RF-DLLRF-01:Q:SL:REF',
            'ARef': 'BR-RF-DLLRF-01:SL:REF:AMP',
            'PRef': 'BR-RF-DLLRF-01:SL:REF:PHS',
            'IInp': 'BR-RF-DLLRF-01:I:SL:INP',
            'QInp': 'BR-RF-DLLRF-01:Q:SL:INP',
            'AInp': 'BR-RF-DLLRF-01:SL:INP:AMP',
            'PInp': 'BR-RF-DLLRF-01:SL:INP:PHS',
            'IErr': 'BR-RF-DLLRF-01:I:SL:ERR',
            'QErr': 'BR-RF-DLLRF-01:Q:SL:ERR',
            'AErr': 'BR-RF-DLLRF-01:SL:ERR:AMP',
            'PErr': 'BR-RF-DLLRF-01:SL:ERR:PHS',
            'ASet': ['BR-RF-DLLRF-01:mV:AL:REF', 'RA-RaBO01:RF-LLRF:AmpVCav'],
            'PSet': 'BR-RF-DLLRF-01:PL:REF',
            'AInc': 'BR-RF-DLLRF-01:AMPREF:INCRATE',
            'PInc': 'BR-RF-DLLRF-01:PHSREF:INCRATE',
        },
        'Tun': {
            'Auto': 'BR-RF-DLLRF-01:TUNE',
            'DTune': 'BR-RF-DLLRF-01:DTune-RB',
            'DPhase': 'BR-RF-DLLRF-01:TUNE:DEPHS',
            'Acting': 'BR-RF-DLLRF-01:TUNE:OUT',
            'Pl1Down': 'BR-RF-DLLRF-01:PLG1:MOVE:DN',
            'Pl1Up': 'BR-RF-DLLRF-01:PLG1:MOVE:UP',
            'Pl2Down': 'BR-RF-DLLRF-01:PLG2:MOVE:DN',
            'Pl2Up': 'BR-RF-DLLRF-01:PLG2:MOVE:UP',
            'PlM1Curr': 'RA-RaBO01:RF-CavPlDrivers:Dr1Current-Mon',
            'PlM2Curr': 'RA-RaBO01:RF-CavPlDrivers:Dr2Current-Mon',
        },
        'FFlat': {
            'Sts': 'BR-RF-DLLRF-01:FF:ON',
            'Auto': 'BR-RF-DLLRF-01:FF',
            'Pos': 'BR-RF-DLLRF-01:FF:POS',
            'Gain1': 'BR-RF-DLLRF-01:FF:GAIN:CELL2',
            'Gain2': 'BR-RF-DLLRF-01:FF:GAIN:CELL4',
            'Cell1': 'BR-RF-DLLRF-01:FF:CELL2',
            'Cell2': 'BR-RF-DLLRF-01:FF:CELL4',
            'Deadband': 'BR-RF-DLLRF-01:FF:DEADBAND',
            'Err': 'BR-RF-DLLRF-01:FF:ERR',
        },
        'PwrMtr': {
            'Cavity Power': {
                'W': 'BO-05D:RF-P5Cav:Cell3Pwr-Mon',
                'dBm': 'BO-05D:RF-P5Cav:Cell3PwrdBm-Mon',
                'mV': 'BR-RF-DLLRF-01:CAV:AMP',
                'color': 'blue',
            },
            'Power Forward': {
                'W': 'BO-05D:RF-P5Cav:PwrFwd-Mon',
                'dBm': 'BO-05D:RF-P5Cav:PwrFwddBm-Mon',
                'mV': 'BR-RF-DLLRF-01:FWDCAV:AMP',
                'color': 'darkGreen',
            },
            'Power Reverse': {
                'W': 'BO-05D:RF-P5Cav:PwrRev-Mon',
                'dBm': 'BO-05D:RF-P5Cav:PwrRevdBm-Mon',
                'mV': 'BR-RF-DLLRF-01:REVCAV:AMP',
                'color': 'red',
            },
        },
        'CavVGap': 'BO-05D:RF-P5Cav:AmpVCav-Mon',
        'TempMon': {
            'Temp.': {
                'Cells': {
                    'Cell 1': 'BO-05D:RF-P5Cav:Cylin1T-Mon',
                    'Cell 2': 'BO-05D:RF-P5Cav:Cylin2T-Mon',
                    'Cell 3': 'BO-05D:RF-P5Cav:Cylin3T-Mon',
                    'Cell 4': 'BO-05D:RF-P5Cav:Cylin4T-Mon',
                    'Cell 5': 'BO-05D:RF-P5Cav:Cylin5T-Mon',
                },
            },
        },
    },
    'SI': {
        'Emergency': 'RA-RaSIA02:RF-IntlkCtrl:EStop-Mon',
        'Sirius Intlk': 'RA-RaSIA02:RF-IntlkCtrl:IntlkSirius-Mon',
        'LLRF Intlk': 'RA-RaSIA01:RF-LLRF:Intlk-Mon',
        'LLRF Intlk Details': {
            'Inputs': {
                'Input': {
                    'Status': {
                        '0': 'SR-RF-DLLRF-01:ILK:0',
                        '1': 'SR-RF-DLLRF-01:ILK:1',
                        '2': 'SR-RF-DLLRF-01:ILK:2',
                        '3': 'SR-RF-DLLRF-01:ILK:3',
                        '4': 'SR-RF-DLLRF-01:ILK:4',
                        '5': 'SR-RF-DLLRF-01:ILK:5',
                        '6': 'SR-RF-DLLRF-01:ILK:6',
                        '7': 'SR-RF-DLLRF-01:ILK:7',
                        'Mon': 'SR-RF-DLLRF-01:Intlk-Mon',
                    },
                    'Labels': (
                        'Rev Out SSA 1',
                        'Rev Out SSA 2',
                        'Not Used (RefSSA3)',
                        'Not Used (RevSSA4)',
                        'Rev Cavity',
                        'Not Used (Ext LLRF1)',
                        'Not Used (Ext LLRF2)',
                        'Not Used (Ext LLRF3)',
                        'Manual',
                        'PLC',
                        'Plunger 1 End Sw Up',
                        'Plunger 1 End Sw Down',
                        'Plunger 2 End Sw Up',
                        'Plunger 2 End Sw Down',
                    ),
                },
                'Fast Input': {
                    'Status': {
                        '0': 'SR-RF-DLLRF-01:FAST:ILK:0',
                        '1': 'SR-RF-DLLRF-01:FAST:ILK:1',
                        '2': 'SR-RF-DLLRF-01:FAST:ILK:2',
                        '3': 'SR-RF-DLLRF-01:FAST:ILK:3',
                        '4': 'SR-RF-DLLRF-01:FAST:ILK:4',
                        '5': 'SR-RF-DLLRF-01:FAST:ILK:5',
                        '6': 'SR-RF-DLLRF-01:FAST:ILK:6',
                        '7': 'SR-RF-DLLRF-01:FAST:ILK:7',
                        'Mon': 'SR-RF-DLLRF-01:FASTINLK-MON',
                    },
                    'Labels': (
                        'Cavity Voltage',
                        'Cavity Fwd',
                        'SSA 1 Out Fwd',
                        'Cell 2 Voltage (RFIN7)',
                        'Cell 6 Voltage (RFIN8)',
                        'SSA 2 Out Fwd (RFIN9)',
                        'SSA 2 Rev Fwd (RFIN10)',
                        'Pre-Drive 1 In (RFIN11)',
                        'Pre-Drive 1 Out (RFIN12)',
                        'Pre-Drive 2 In (RFIN13)',
                        'Pre-Drive 2 Out (RFIN14)',
                        'Circulator Out Fwd (RFIN15)',
                        'LLRF Beam Trip',
                    ),
                },
            },
            'Timestamps': {
                '1': 'SR-RF-DLLRF-01:TS1',
                '2': 'SR-RF-DLLRF-01:TS2',
                '3': 'SR-RF-DLLRF-01:TS3',
                '4': 'SR-RF-DLLRF-01:TS4',
                '5': 'SR-RF-DLLRF-01:TS5',
                '6': 'SR-RF-DLLRF-01:TS6',
                '7': 'SR-RF-DLLRF-01:TS7',
            }
        },
        'Reset': {
            'Global': 'RA-RaSIA02:RF-Intlk:Reset-Cmd',
            'LLRF': 'SR-RF-DLLRF-01:Reset-Cmd',
        },
        'Cav Sts': {
            'Geral': 'SI-02SB:RF-P7Cav:Sts-Mon',
            'Temp': {
                'Cells': (
                    ('SI-02SB:RF-P7Cav:Cylin1T-Mon', 'blue'),
                    ('SI-02SB:RF-P7Cav:Cylin2T-Mon', 'red'),
                    ('SI-02SB:RF-P7Cav:Cylin3T-Mon', 'yellow'),
                    ('SI-02SB:RF-P7Cav:Cylin4T-Mon', 'darkGreen'),
                    ('SI-02SB:RF-P7Cav:Cylin5T-Mon', 'magenta'),
                    ('SI-02SB:RF-P7Cav:Cylin6T-Mon', 'darkCyan'),
                    ('SI-02SB:RF-P7Cav:Cylin7T-Mon', 'darkRed'),
                ),
                'Cells Limits PVs': ('SI-02SB:RF-P7Cav:Cylin1TLowerLimit-Cte',
                                     'SI-02SB:RF-P7Cav:Cylin1TUpperLimit-Cte'),
                'Cells Limits': [0.0, 0.0],
                'Coupler': ('SI-02SB:RF-P7Cav:CoupT-Mon', 'black'),
                'Coupler Limits PVs': ('SI-02SB:RF-P7Cav:CoupTLowerLimit-Cte',
                                       'SI-02SB:RF-P7Cav:CoupTUpperLimit-Cte'),
                'Coupler Limits': [0.0, 0.0],
                'Discs': (
                    'SI-02SB:RF-P7Cav:Disc1Tms-Mon',
                    'SI-02SB:RF-P7Cav:Disc2Tms-Mon',
                    'SI-02SB:RF-P7Cav:Disc3Tms-Mon',
                    'SI-02SB:RF-P7Cav:Disc4Tms-Mon',
                    'SI-02SB:RF-P7Cav:Disc5Tms-Mon',
                    'SI-02SB:RF-P7Cav:Disc6Tms-Mon',
                    'SI-02SB:RF-P7Cav:Disc7Tms-Mon',
                    'SI-02SB:RF-P7Cav:Disc8Tms-Mon',
                ),
            },
            'FlwRt': (
                'SI-02SB:RF-P7Cav:HDFlwRt1-Mon',
                'SI-02SB:RF-P7Cav:HDFlwRt2-Mon',
                'SI-02SB:RF-P7Cav:HDFlwRt3-Mon',
            ),
            'Vac': {
                'Cells': 'SI-02SB:VA-CCG-CAV:Pressure-Mon',
                'Cond': 'SR-RF-DLLRF-01:VACUUM',
                'Cells ok': 'SI-02SB:RF-P7Cav:Pressure-Mon',
                'Coupler ok': 'SI-02SB:RF-P7Cav:CoupPressure-Mon',
            }
        },
        'TL Sts': {
            'Geral': 'RA-TLSIA:RF-TrLine:Sts-Mon',
            'Circ TIn': 'RA-TLSIA:RF-Circulator:Tin-Mon',
            'Circ TOut': 'RA-TLSIA:RF-Circulator:Tout-Mon',
            'Circ Arc': 'RA-TLSIA:RF-Circulator:Arc-Mon',
            'Load Arc': 'RA-TLSIA:RF-Load:Arc-Mon',
            'Circ FlwRt': 'RA-TLSIA:RF-Circulator:FlwRt-Mon',
            'Load FlwRt': 'RA-TLSIA:RF-Load:FlwRt-Mon',
            'Circ Intlk': 'RA-TLSIA:RF-Circulator:IntlkOp-Mon',
            'Circ Limits': (19.0, 23.0),
        },
        'SSA': {
            '1': {
                'Name': 'SSA 01',
                'Status': 'RA-ToSIA01:RF-SSAmpTower:Sts-Mon',
                'Power': 'RA-ToSIA01:RF-SSAmpTower:PwrFwdOut1-Mon',
                'SRC 1': {
                    'Label': 'AC TDK',
                    'PV': 'RA-ToSIA01:RF-ACPanel:PwrAC-Sts'
                },
                'SRC 2': {
                    'Label': 'DC TDK',
                    'PV': 'RA-ToSIA01:RF-TDKSource:PwrDC-Sts',
                },
                'PinSw': 'RA-RaSIA01:RF-LLRFPreAmp-1:PINSw1-Mon',
                'PreDrive': 'SR-RF-DLLRF-01:INPRE1:AMP',
            },
            '2': {
                'Name': 'SSA 02',
                'Status': 'RA-ToSIA02:RF-SSAmpTower:Sts-Mon',
                'Power': 'RA-ToSIA02:RF-SSAmpTower:PwrFwdOut4-Mon',
                'SRC 1': {
                    'Label': 'AC TDK',
                    'PV': 'RA-ToSIA02:RF-ACPanel:PwrAC-Sts',
                },
                'SRC 2': {
                    'Label': 'DC TDK',
                    'PV': 'RA-ToSIA02:RF-TDKSource:PwrDC-Sts',
                },
                'PinSw': 'RA-RaSIA01:RF-LLRFPreAmp-1:PINSw2-Mon',
                'PreDrive': 'SR-RF-DLLRF-01:INPRE2:AMP',
            }
        },
        'SL': {
            'Enbl': 'SR-RF-DLLRF-01:SL',
            'Mode': 'SR-RF-DLLRF-01:MODE',
            'IRef': 'SR-RF-DLLRF-01:I:SL:REF',
            'QRef': 'SR-RF-DLLRF-01:Q:SL:REF',
            'ARef': 'SR-RF-DLLRF-01:SL:REF:AMP',
            'PRef': 'SR-RF-DLLRF-01:SL:REF:PHS',
            'IInp': 'SR-RF-DLLRF-01:I:SL:INP',
            'QInp': 'SR-RF-DLLRF-01:Q:SL:INP',
            'AInp': 'SR-RF-DLLRF-01:SL:INP:AMP',
            'PInp': 'SR-RF-DLLRF-01:SL:INP:PHS',
            'IErr': 'SR-RF-DLLRF-01:I:SL:ERR',
            'QErr': 'SR-RF-DLLRF-01:Q:SL:ERR',
            'AErr': 'SR-RF-DLLRF-01:SL:ERR:AMP',
            'PErr': 'SR-RF-DLLRF-01:SL:ERR:PHS',
            'ASet': ['SR-RF-DLLRF-01:mV:AL:REF', 'RA-RaSIA01:RF-LLRF:AmpVCav'],
            'PSet': 'SR-RF-DLLRF-01:PL:REF',
            'AInc': 'SR-RF-DLLRF-01:AMPREF:INCRATE',
            'PInc': 'SR-RF-DLLRF-01:PHSREF:INCRATE',
        },
        'Tun': {
            'Auto': 'SR-RF-DLLRF-01:TUNE',
            'DTune': 'SR-RF-DLLRF-01:DTune-RB',
            'DPhase': 'SR-RF-DLLRF-01:TUNE:DEPHS',
            'Acting': 'SR-RF-DLLRF-01:TUNE:OUT',
            'Pl1Down': 'SR-RF-DLLRF-01:PLG1:MOVE:DN',
            'Pl1Up': 'SR-RF-DLLRF-01:PLG1:MOVE:UP',
            'Pl2Down': 'SR-RF-DLLRF-01:PLG2:MOVE:DN',
            'Pl2Up': 'SR-RF-DLLRF-01:PLG2:MOVE:UP',
            'PlM1Curr': 'RA-RaSIA01:RF-CavPlDrivers:Dr1Current-Mon',
            'PlM2Curr': 'RA-RaSIA01:RF-CavPlDrivers:Dr2Current-Mon',
        },
        'FFlat': {
            'Sts': 'SR-RF-DLLRF-01:FF:ON',
            'Auto': 'SR-RF-DLLRF-01:FF',
            'Pos': 'SR-RF-DLLRF-01:FF:POS',
            'Gain1': 'SR-RF-DLLRF-01:FF:GAIN:CELL2',
            'Gain2': 'SR-RF-DLLRF-01:FF:GAIN:CELL4',
            'Cell1': 'SR-RF-DLLRF-01:FF:CELL2',
            'Cell2': 'SR-RF-DLLRF-01:FF:CELL4',
            'Deadband': 'SR-RF-DLLRF-01:FF:DEADBAND',
            'Err': 'SR-RF-DLLRF-01:FF:ERR',
        },
        'PwrMtr': {
            'Cav - Cell 2': {
                'W': 'SI-02SB:RF-P7Cav:PwrCell2-Mon',
                'dBm': 'SI-02SB:RF-P7Cav:PwrCell2dBm-Mon',
                'mV': 'SR-RF-DLLRF-01:CELL2:AMP',
                'color': 'darkRed',
            },
            'Cav - Cell 4': {
                'W': 'SI-02SB:RF-P7Cav:PwrCell4-Mon',
                'dBm': 'SI-02SB:RF-P7Cav:PwrCell4dBm-Mon',
                'mV': 'SR-RF-DLLRF-01:CAV:AMP',
                'color': 'black',
            },
            'Cav - Cell 6': {
                'W': 'SI-02SB:RF-P7Cav:PwrCell6-Mon',
                'dBm': 'SI-02SB:RF-P7Cav:PwrCell6dBm-Mon',
                'mV': 'SR-RF-DLLRF-01:CELL6:AMP',
                'color': 'darkBlue',
            },
            'Cav - Coup Fwd': {
                'W': 'SI-02SB:RF-P7Cav:PwrFwd-Mon',
                'dBm': 'SI-02SB:RF-P7Cav:PwrFwddBm-Mon',
                'mV': 'SR-RF-DLLRF-01:FWDCAV:AMP',
                'color': 'blue',
            },
            'Cav - Coup Rev': {
                'W': 'SI-02SB:RF-P7Cav:PwrRev-Mon',
                'dBm': 'SI-02SB:RF-P7Cav:PwrRevdBm-Mon',
                'mV': 'SR-RF-DLLRF-01:REVCAV:AMP',
                'color': 'red',
            },
            'SSA1 - Fwd Out': {
                'W': 'RA-ToSIA01:RF-SSAmpTower:PwrFwdOutLLRF-Mon',
                'dBm': 'RA-ToSIA01:RF-SSAmpTower:PwrFwdOutdBm-Mon',
                'mV': 'SR-RF-DLLRF-01:FWDSSA1:AMP',
                'color': 'magenta',
            },
            'SSA1 - Rev Out': {
                'W': 'RA-ToSIA01:RF-SSAmpTower:PwrRevOutLLRF-Mon',
                'dBm': 'RA-ToSIA01:RF-SSAmpTower:PwrRevOutdBm-Mon',
                'mV': 'SR-RF-DLLRF-01:REVSSA1:AMP',
                'color': 'darkGreen',
            },
            'SSA2 - Fwd Out': {
                'W': 'RA-ToSIA02:RF-SSAmpTower:PwrFwdOutLLRF-Mon',
                'dBm': 'RA-ToSIA02:RF-SSAmpTower:PwrFwdOutdBm-Mon',
                'mV': 'SR-RF-DLLRF-01:FWDSSA2:AMP',
                'color': 'yellow',
            },
            'SSA2 - Rev Out': {
                'W': 'RA-ToSIA02:RF-SSAmpTower:PwrRevOutLLRF-Mon',
                'dBm': 'RA-ToSIA02:RF-SSAmpTower:PwrRevOutdBm-Mon',
                'mV': 'SR-RF-DLLRF-01:REVSSA2:AMP',
                'color': 'cyan',
            },
            'Circ - Fwd Out': {
                'W': 'RA-TL:RF-Circulator-SIA:PwrFwdOut-Mon',
                'dBm': 'RA-TL:RF-Circulator-SIA:PwrFwdOutdBm-Mon',
                'mV': 'SR-RF-DLLRF-01:FWDCIRC:AMP',
                'color': 'darkCyan',
            },
        },
        'CavVGap': 'SI-02SB:RF-P7Cav:AmpVCav-Mon',
        'TempMon': {
            'Temp.': {
                'Cells': {
                    'Cell 1': 'SI-02SB:RF-P7Cav:Cylin1T-Mon',
                    'Cell 2': 'SI-02SB:RF-P7Cav:Cylin2T-Mon',
                    'Cell 3': 'SI-02SB:RF-P7Cav:Cylin3T-Mon',
                    'Cell 4': 'SI-02SB:RF-P7Cav:Cylin4T-Mon',
                    'Cell 5': 'SI-02SB:RF-P7Cav:Cylin5T-Mon',
                    'Cell 6': 'SI-02SB:RF-P7Cav:Cylin6T-Mon',
                    'Cell 7': 'SI-02SB:RF-P7Cav:Cylin7T-Mon',
                },
            },
            'Water Temp.': {
                'Cells': {
                    'Cell 1': 'SI-02SB:RF-P7Cav:Cylin1WT-Mon',
                    'Cell 2': 'SI-02SB:RF-P7Cav:Cylin2WT-Mon',
                    'Cell 3': 'SI-02SB:RF-P7Cav:Cylin3WT-Mon',
                    'Cell 4': 'SI-02SB:RF-P7Cav:Cylin4WT-Mon',
                    'Cell 5': 'SI-02SB:RF-P7Cav:Cylin5WT-Mon',
                    'Cell 6': 'SI-02SB:RF-P7Cav:Cylin6WT-Mon',
                    'Cell 7': 'SI-02SB:RF-P7Cav:Cylin7WT-Mon',
                },
                'Discs': {
                    'Disc 1': 'SI-02SB:RF-P7Cav:Disc1WT-Mon',
                    'Disc 2': 'SI-02SB:RF-P7Cav:Disc2WT-Mon',
                    'Disc 3': 'SI-02SB:RF-P7Cav:Disc3WT-Mon',
                    'Disc 4': 'SI-02SB:RF-P7Cav:Disc4WT-Mon',
                    'Disc 5': 'SI-02SB:RF-P7Cav:Disc5WT-Mon',
                    'Disc 6': 'SI-02SB:RF-P7Cav:Disc6WT-Mon',
                    'Disc 7': 'SI-02SB:RF-P7Cav:Disc7WT-Mon',
                    'Disc 8': 'SI-02SB:RF-P7Cav:Disc8WT-Mon',
                },
                'Input + Plungers + Coupler': {
                    'Input': 'SI-02SB:RF-P7Cav:WInT-Mon',
                    'Plunger 1': 'SI-02SB:RF-P7Cav:Pl1WT-Mon',
                    'Plunger 2': 'SI-02SB:RF-P7Cav:Pl2WT-Mon',
                    'Coupler': 'SI-02SB:RF-P7Cav:CoupWT-Mon',
                },
            },
            'Water dTemp.': {
                'Cells': {
                    'Cell 1': 'SI-02SB:RF-P7Cav:Cylin1WdT-Mon',
                    'Cell 2': 'SI-02SB:RF-P7Cav:Cylin2WdT-Mon',
                    'Cell 3': 'SI-02SB:RF-P7Cav:Cylin3WdT-Mon',
                    'Cell 4': 'SI-02SB:RF-P7Cav:Cylin4WdT-Mon',
                    'Cell 5': 'SI-02SB:RF-P7Cav:Cylin5WdT-Mon',
                    'Cell 6': 'SI-02SB:RF-P7Cav:Cylin6WdT-Mon',
                    'Cell 7': 'SI-02SB:RF-P7Cav:Cylin7WdT-Mon',
                },
                'Discs': {
                    'Disc 1': 'SI-02SB:RF-P7Cav:Disc1WdT-Mon',
                    'Disc 2': 'SI-02SB:RF-P7Cav:Disc2WdT-Mon',
                    'Disc 3': 'SI-02SB:RF-P7Cav:Disc3WdT-Mon',
                    'Disc 4': 'SI-02SB:RF-P7Cav:Disc4WdT-Mon',
                    'Disc 5': 'SI-02SB:RF-P7Cav:Disc5WdT-Mon',
                    'Disc 6': 'SI-02SB:RF-P7Cav:Disc6WdT-Mon',
                    'Disc 7': 'SI-02SB:RF-P7Cav:Disc7WdT-Mon',
                    'Disc 8': 'SI-02SB:RF-P7Cav:Disc8WdT-Mon',
                },
            },
            'Dissip. Power': {
                'Cells': {
                    'Cell 1': 'SI-02SB:RF-P7Cav:PwrDissCell1-Mon',
                    'Cell 2': 'SI-02SB:RF-P7Cav:PwrDissCell2-Mon',
                    'Cell 3': 'SI-02SB:RF-P7Cav:PwrDissCell3-Mon',
                    'Cell 4': 'SI-02SB:RF-P7Cav:PwrDissCell4-Mon',
                    'Cell 5': 'SI-02SB:RF-P7Cav:PwrDissCell5-Mon',
                    'Cell 6': 'SI-02SB:RF-P7Cav:PwrDissCell6-Mon',
                    'Cell 7': 'SI-02SB:RF-P7Cav:PwrDissCell7-Mon',
                },
                'Discs': {
                    'Disc 1': 'SI-02SB:RF-P7Cav:PwrDissDisc1-Mon',
                    'Disc 2': 'SI-02SB:RF-P7Cav:PwrDissDisc2-Mon',
                    'Disc 3': 'SI-02SB:RF-P7Cav:PwrDissDisc3-Mon',
                    'Disc 4': 'SI-02SB:RF-P7Cav:PwrDissDisc4-Mon',
                    'Disc 5': 'SI-02SB:RF-P7Cav:PwrDissDisc5-Mon',
                    'Disc 6': 'SI-02SB:RF-P7Cav:PwrDissDisc6-Mon',
                    'Disc 7': 'SI-02SB:RF-P7Cav:PwrDissDisc7-Mon',
                    'Disc 8': 'SI-02SB:RF-P7Cav:PwrDissDisc8-Mon',
                },
            },
            'Power': {
                'Cell 1': 'SI-02SB:RF-P7Cav:PwrWtCell1-Mon',
                'Cell 2': 'SI-02SB:RF-P7Cav:PwrWtCell2-Mon',
                'Cell 3': 'SI-02SB:RF-P7Cav:PwrWtCell3-Mon',
                'Cell 4': 'SI-02SB:RF-P7Cav:PwrWtCell4-Mon',
                'Cell 5': 'SI-02SB:RF-P7Cav:PwrWtCell5-Mon',
                'Cell 6': 'SI-02SB:RF-P7Cav:PwrWtCell6-Mon',
                'Cell 7': 'SI-02SB:RF-P7Cav:PwrWtCell7-Mon',
                # 'Total': 'SI-02SB:RF-P7Cav:PwrWtTotal-Mon',
                # 'Fwd': 'RA-RaSIA01:RF-RFCalSys:PwrW2-Mon',
            },
        }
    },
}
