from .TBMagnetControlWindow import TBMagnetControlWindow
from .BoosterMagnetControlWindow import BoosterMagnetControlWindow
from .TSMagnetControlWindow import TSMagnetControlWindow
from .SIMagnetControlWindow import SIMagnetControlWindow
