from .TBMagnetControlWindow import TBMagnetControlWindow
from .BoosterMagnetControlWindow import BoosterMagnetControlWindow
from .ToSiriusMagnetControlWindow import ToSiriusMagnetControlWindow
from .SiriusMagnetControlWindow import SiriusMagnetControlWindow
