name: Documentation

on:
  pull_request:
    branches:
      - master

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install pyqt5
        run: pip install pyqt5==5.15.9

      - name: Install siriushla dependencies
        run: pip install -r pyqt-apps/requirements.txt

      - name: Install siriushla
        run: pip install pyqt-apps/

      - name: Install docs dependencies
        run: pip install -r pyqt-apps/docs/doc_requirements.txt

      - name: Build HTML
        run: sphinx-build -b html pyqt-apps/docs/source/ ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
